server:
  port: 8002

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hospital-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    topics:
      patients: patients-topic
      appointments: appointments-topic
      status: patient-status-topic
