server:
  port: 8001

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  cors:
    allowedOrigins:
      - http://localhost:7001
      - http://localhost:7002

  kafka:
    topics:
      patients: patients-topic
      appointments: appointments-topic
      status: patient-status-topic
